/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => FileMoverPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  targetFolder: "Archive",
  enableMoveContext: true,
  enableCreateTodayFolder: true,
  enableCreateTodayNote: true,
  todayNoteFolder: "",
  todayNoteTemplate: "",
  enableRibbonTodayNote: true
};
var FileMoverPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.ribbonEl = null;
  }
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new FileMoverSettingTab(this.app, this));
    this.addCommand({
      id: "create-today-folder",
      name: "\u4ECA\u65E5\u306E\u65E5\u4ED8\u306E\u30D5\u30A9\u30EB\u30C0\u3092\u4F5C\u6210",
      checkCallback: (checking) => {
        if (!this.settings.enableCreateTodayFolder)
          return false;
        if (!checking)
          void this.createTodayFolder(this.app.vault.getRoot());
        return true;
      }
    });
    this.addCommand({
      id: "create-today-note",
      name: "\u30C7\u30A4\u30EA\u30FC\u30CE\u30FC\u30C8\u3092\u4F5C\u6210",
      checkCallback: (checking) => {
        if (!this.settings.enableCreateTodayNote)
          return false;
        if (!checking)
          void this.createTodayNote(this.app.vault.getRoot());
        return true;
      }
    });
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        var _a;
        const targetFolder = file instanceof import_obsidian.TFolder ? file : (_a = file == null ? void 0 : file.parent) != null ? _a : this.app.vault.getRoot();
        if (this.settings.enableMoveContext) {
          menu.addItem((item) => {
            item.setTitle(this.getMoveLabel()).setIcon("folder-plus").onClick(async () => {
              if (file instanceof import_obsidian.TFile || file instanceof import_obsidian.TFolder) {
                await this.moveFileOrFolder(file);
              }
            });
          });
        }
        if (this.settings.enableCreateTodayFolder) {
          menu.addItem((item) => {
            item.setTitle("\u4ECA\u65E5\u306E\u65E5\u4ED8\u306E\u30D5\u30A9\u30EB\u30C0\u3092\u4F5C\u6210").setIcon("folder").onClick(async () => {
              await this.createTodayFolder(targetFolder);
            });
          });
        }
        if (this.settings.enableCreateTodayNote) {
          menu.addItem((item) => {
            item.setTitle("\u30C7\u30A4\u30EA\u30FC\u30CE\u30FC\u30C8\u3092\u4F5C\u6210").setIcon("file-plus").onClick(async () => {
              await this.createTodayNote(targetFolder);
            });
          });
        }
      })
    );
    this.registerEvent(
      this.app.workspace.on("files-menu", (menu, files) => {
        if (!this.settings.enableMoveContext)
          return;
        menu.addItem((item) => {
          item.setTitle(this.getMoveLabel()).setIcon("folder-plus").onClick(async () => {
            let movedCount = 0;
            for (const file of files) {
              if (file instanceof import_obsidian.TFile || file instanceof import_obsidian.TFolder) {
                await this.moveFileOrFolder(file);
                movedCount++;
              }
            }
            if (movedCount > 1) {
              new import_obsidian.Notice(`${movedCount} \u4EF6\u3092 ${this.settings.targetFolder} \u306B\u79FB\u884C\u3057\u307E\u3057\u305F`);
            }
          });
        });
      })
    );
    this.refreshRibbonButton();
  }
  onunload() {
    this.removeRibbonButton();
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  getMoveLabel() {
    return this.settings.targetFolder ? `\u300C${this.settings.targetFolder}\u300D\u306B\u79FB\u884C` : "\u6307\u5B9A\u30D5\u30A9\u30EB\u30C0\u306B\u79FB\u884C";
  }
  async moveFileOrFolder(file) {
    if (!this.settings.targetFolder) {
      new import_obsidian.Notice("\u79FB\u884C\u5148\u30D5\u30A9\u30EB\u30C0\u304C\u8A2D\u5B9A\u3055\u308C\u3066\u3044\u307E\u305B\u3093\u3002\u8A2D\u5B9A\u304B\u3089\u79FB\u884C\u5148\u30D5\u30A9\u30EB\u30C0\u3092\u6307\u5B9A\u3057\u3066\u304F\u3060\u3055\u3044\u3002");
      return;
    }
    try {
      const targetPath = await this.getTargetPath(file);
      if (file instanceof import_obsidian.TFile) {
        await this.moveFile(file, targetPath);
      } else {
        await this.moveFolder(file, targetPath);
      }
      new import_obsidian.Notice(`${file.name} \u3092 ${this.settings.targetFolder} \u306B\u79FB\u884C\u3057\u307E\u3057\u305F`);
    } catch (error) {
      new import_obsidian.Notice(`\u79FB\u884C\u306B\u5931\u6557\u3057\u307E\u3057\u305F: ${this.getErrorMessage(error)}`);
      console.error("File move error:", error);
    }
  }
  async getTargetPath(file) {
    const targetPath = (0, import_obsidian.normalizePath)(`${this.settings.targetFolder}/${file.path}`);
    const targetDir = targetPath.substring(0, targetPath.lastIndexOf("/"));
    await this.ensureDirectoryExists(targetDir);
    return targetPath;
  }
  async ensureDirectoryExists(dirPath) {
    const dirs = (0, import_obsidian.normalizePath)(dirPath).split("/");
    let currentPath = "";
    for (const dir of dirs) {
      if (!dir)
        continue;
      currentPath += (currentPath ? "/" : "") + dir;
      const existingFolder = this.app.vault.getAbstractFileByPath(currentPath);
      if (!existingFolder) {
        await this.app.vault.createFolder(currentPath);
      }
    }
  }
  async moveFile(file, targetPath) {
    let finalPath = targetPath;
    let counter = 1;
    while (this.app.vault.getAbstractFileByPath(finalPath)) {
      const extension = file.extension ? `.${file.extension}` : "";
      const dir = finalPath.substring(0, finalPath.lastIndexOf("/"));
      finalPath = `${dir}/${file.basename} (${counter})${extension}`;
      counter++;
    }
    await this.app.fileManager.renameFile(file, finalPath);
  }
  async moveFolder(folder, targetPath) {
    let finalPath = targetPath;
    let counter = 1;
    while (this.app.vault.getAbstractFileByPath(finalPath)) {
      const parentDir = finalPath.substring(0, finalPath.lastIndexOf("/"));
      finalPath = `${parentDir}/${folder.name} (${counter})`;
      counter++;
    }
    await this.app.fileManager.renameFile(folder, finalPath);
  }
  formatToday() {
    const now = new Date();
    const yyyy = now.getFullYear();
    const mm = String(now.getMonth() + 1).padStart(2, "0");
    const dd = String(now.getDate()).padStart(2, "0");
    return `${yyyy}-${mm}-${dd}`;
  }
  formatTime() {
    const now = new Date();
    const hh = String(now.getHours()).padStart(2, "0");
    const min = String(now.getMinutes()).padStart(2, "0");
    return `${hh}:${min}`;
  }
  renderTemplate(content, title) {
    const date = this.formatToday();
    const time = this.formatTime();
    return content.replace(/\{\{\s*date\s*\}\}/gi, date).replace(/\{\{\s*time\s*\}\}/gi, time).replace(/\{\{\s*title\s*\}\}/gi, title);
  }
  async getTodayNoteTemplateContent(baseName) {
    const templatePath = (this.settings.todayNoteTemplate || "").trim();
    if (!templatePath)
      return "";
    const normalizedPath = (0, import_obsidian.normalizePath)(templatePath.endsWith(".md") ? templatePath : `${templatePath}.md`);
    const templateFile = this.app.vault.getAbstractFileByPath(normalizedPath);
    if (!(templateFile instanceof import_obsidian.TFile)) {
      new import_obsidian.Notice(`\u30C6\u30F3\u30D7\u30EC\u30FC\u30C8\u304C\u898B\u3064\u304B\u308A\u307E\u305B\u3093: ${normalizedPath}`, 5e3);
      return "";
    }
    const content = await this.app.vault.read(templateFile);
    return this.renderTemplate(content, baseName);
  }
  async createTodayFolder(parent) {
    const parentPath = (parent == null ? void 0 : parent.path) ? parent.path : "/";
    const baseName = this.formatToday();
    let folderPath = (0, import_obsidian.normalizePath)(parentPath === "/" || parentPath === "" ? baseName : `${parentPath}/${baseName}`);
    let suffix = 0;
    while (this.app.vault.getAbstractFileByPath(folderPath)) {
      suffix += 1;
      const name = `${baseName}_${suffix}`;
      folderPath = (0, import_obsidian.normalizePath)(parentPath === "/" || parentPath === "" ? name : `${parentPath}/${name}`);
    }
    try {
      await this.app.vault.createFolder(folderPath);
      new import_obsidian.Notice(`\u4F5C\u6210: ${folderPath}`);
      const untitledBase = "\u7121\u984C\u306E\u30D5\u30A1\u30A4\u30EB";
      const ext = ".md";
      let notePath = (0, import_obsidian.normalizePath)(`${folderPath}/${untitledBase}${ext}`);
      let noteCounter = 1;
      while (this.app.vault.getAbstractFileByPath(notePath)) {
        notePath = (0, import_obsidian.normalizePath)(`${folderPath}/${untitledBase} (${noteCounter})${ext}`);
        noteCounter += 1;
      }
      const noteFile = await this.app.vault.create(notePath, "");
      new import_obsidian.Notice(`\u4F5C\u6210: ${notePath}`);
      const leaf = this.app.workspace.getLeaf(true);
      await leaf.openFile(noteFile);
    } catch (error) {
      console.error(error);
      new import_obsidian.Notice("\u30D5\u30A9\u30EB\u30C0\u4F5C\u6210\u306B\u5931\u6557\u3057\u307E\u3057\u305F\u3002\u30B3\u30F3\u30BD\u30FC\u30EB\u3092\u78BA\u8A8D\u3057\u3066\u304F\u3060\u3055\u3044\u3002", 5e3);
    }
  }
  async createTodayNote(parent, folderOverride) {
    const baseName = this.formatToday();
    const overridePath = typeof folderOverride === "string" ? folderOverride.trim() : "";
    let dirPath = "";
    if (overridePath) {
      const normalizedOverride = (0, import_obsidian.normalizePath)(overridePath);
      if (normalizedOverride && normalizedOverride !== ".") {
        await this.ensureDirectoryExists(normalizedOverride);
        dirPath = normalizedOverride;
      }
    } else {
      const parentPath = (parent == null ? void 0 : parent.path) ? parent.path : "/";
      dirPath = parentPath === "/" || parentPath === "" ? "" : parentPath;
    }
    if (dirPath === "/")
      dirPath = "";
    const baseDir = dirPath ? `${dirPath}/` : "";
    let notePath = (0, import_obsidian.normalizePath)(`${baseDir}${baseName}.md`);
    let suffix = 0;
    while (this.app.vault.getAbstractFileByPath(notePath)) {
      suffix += 1;
      notePath = (0, import_obsidian.normalizePath)(`${baseDir}${baseName}_${suffix}.md`);
    }
    try {
      const noteContent = await this.getTodayNoteTemplateContent(baseName);
      const noteFile = await this.app.vault.create(notePath, noteContent);
      new import_obsidian.Notice(`\u4F5C\u6210: ${notePath}`);
      const leaf = this.app.workspace.getLeaf(true);
      await leaf.openFile(noteFile);
    } catch (error) {
      console.error(error);
      new import_obsidian.Notice("\u30CE\u30FC\u30C8\u4F5C\u6210\u306B\u5931\u6557\u3057\u307E\u3057\u305F\u3002\u30B3\u30F3\u30BD\u30FC\u30EB\u3092\u78BA\u8A8D\u3057\u3066\u304F\u3060\u3055\u3044\u3002", 5e3);
    }
  }
  removeRibbonButton() {
    var _a;
    (_a = this.ribbonEl) == null ? void 0 : _a.remove();
    this.ribbonEl = null;
  }
  refreshRibbonButton() {
    this.removeRibbonButton();
    if (!this.settings.enableRibbonTodayNote)
      return;
    const ribbon = this.addRibbonIcon("calendar-plus", "\u6307\u5B9A\u30D5\u30A9\u30EB\u30C0\u306B\u4ECA\u65E5\u306E\u65E5\u4ED8\u30CE\u30FC\u30C8\u3092\u4F5C\u6210", async () => {
      const folderPath = (this.settings.todayNoteFolder || "").trim();
      if (!folderPath) {
        new import_obsidian.Notice("\u8A2D\u5B9A\u753B\u9762\u3067\u65E5\u4ED8\u30CE\u30FC\u30C8\u7528\u30D5\u30A9\u30EB\u30C0\u3092\u6307\u5B9A\u3057\u3066\u304F\u3060\u3055\u3044\u3002", 5e3);
        return;
      }
      await this.createTodayNote(null, folderPath);
    });
    ribbon.setAttribute("aria-label", "\u6307\u5B9A\u30D5\u30A9\u30EB\u30C0\u306B\u4ECA\u65E5\u306E\u65E5\u4ED8\u30CE\u30FC\u30C8\u3092\u4F5C\u6210");
    this.ribbonEl = ribbon;
  }
  getErrorMessage(error) {
    return error instanceof Error ? error.message : String(error);
  }
};
var FileMoverSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Right-Click Tools Settings" });
    new import_obsidian.Setting(containerEl).setName("\u79FB\u884C\u5148\u30D5\u30A9\u30EB\u30C0").setDesc("\u30D5\u30A1\u30A4\u30EB\u30FB\u30D5\u30A9\u30EB\u30C0\u3092\u79FB\u884C\u3059\u308B\u5148\u306E\u30D5\u30A9\u30EB\u30C0\u540D\u3092\u6307\u5B9A\u3057\u3066\u304F\u3060\u3055\u3044").addText((text) => text.setPlaceholder("Archive").setValue(this.plugin.settings.targetFolder).onChange(async (value) => {
      this.plugin.settings.targetFolder = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u79FB\u884C\u30E1\u30CB\u30E5\u30FC\u3092\u8868\u793A").setDesc("\u53F3\u30AF\u30EA\u30C3\u30AF\u30E1\u30CB\u30E5\u30FC\u306B\u300C\u6307\u5B9A\u30D5\u30A9\u30EB\u30C0\u306B\u79FB\u884C\u300D\u3092\u8868\u793A\u3057\u307E\u3059").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableMoveContext).onChange(async (value) => {
      this.plugin.settings.enableMoveContext = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u65E5\u4ED8\u30D5\u30A9\u30EB\u30C0\u3092\u4F5C\u6210").setDesc("\u65E5\u4ED8\u3067\u30D5\u30A9\u30EB\u30C0\u3092\u4F5C\u6210\u3059\u308B\u6A5F\u80FD\u3092\u5229\u7528\u53EF\u80FD\u306B\u3057\u307E\u3059").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableCreateTodayFolder).onChange(async (value) => {
      this.plugin.settings.enableCreateTodayFolder = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u65E5\u4ED8\u30CE\u30FC\u30C8\u3092\u4F5C\u6210").setDesc("\u65E5\u4ED8\u3067\u30CE\u30FC\u30C8\u3092\u4F5C\u6210\u3059\u308B\u6A5F\u80FD\u3092\u5229\u7528\u53EF\u80FD\u306B\u3057\u307E\u3059").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableCreateTodayNote).onChange(async (value) => {
      this.plugin.settings.enableCreateTodayNote = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u65E5\u4ED8\u30CE\u30FC\u30C8\u306E\u4FDD\u5B58\u5148\u30D5\u30A9\u30EB\u30C0").setDesc("\u30EA\u30DC\u30F3\u30DC\u30BF\u30F3\u304B\u3089\u4F5C\u6210\u3059\u308B\u65E5\u4ED8\u30CE\u30FC\u30C8\u306E\u4FDD\u5B58\u5148\u3092\u8A2D\u5B9A\u3057\u307E\u3059").addText((text) => text.setPlaceholder("Daily Notes").setValue(this.plugin.settings.todayNoteFolder).onChange(async (value) => {
      this.plugin.settings.todayNoteFolder = value;
      await this.plugin.saveSettings();
      this.plugin.refreshRibbonButton();
    }));
    new import_obsidian.Setting(containerEl).setName("\u65E5\u4ED8\u30CE\u30FC\u30C8\u30C6\u30F3\u30D7\u30EC\u30FC\u30C8").setDesc("\u65E5\u4ED8\u30CE\u30FC\u30C8\u4F5C\u6210\u6642\u306B\u8AAD\u307F\u8FBC\u3080\u30C6\u30F3\u30D7\u30EC\u30FC\u30C8\u30CE\u30FC\u30C8\u306E\u30D1\u30B9\u3092\u8A2D\u5B9A\u3057\u307E\u3059").addText((text) => text.setPlaceholder("9_Template/daily-note").setValue(this.plugin.settings.todayNoteTemplate).onChange(async (value) => {
      this.plugin.settings.todayNoteTemplate = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u30EA\u30DC\u30F3\u306B\u65E5\u4ED8\u30CE\u30FC\u30C8\u30DC\u30BF\u30F3\u3092\u8868\u793A").setDesc("\u4E0A\u90E8\u30EA\u30DC\u30F3\u306B\u6307\u5B9A\u30D5\u30A9\u30EB\u30C0\u306B\u65E5\u4ED8\u30CE\u30FC\u30C8\u3092\u4F5C\u6210\u3059\u308B\u30DC\u30BF\u30F3\u3092\u8868\u793A\u3057\u307E\u3059").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableRibbonTodayNote).onChange(async (value) => {
      this.plugin.settings.enableRibbonTodayNote = value;
      await this.plugin.saveSettings();
      this.plugin.refreshRibbonButton();
    }));
    containerEl.createEl("p", {
      text: "\u6CE8\u610F: \u79FB\u884C\u5148\u30D5\u30A9\u30EB\u30C0\u304C\u5B58\u5728\u3057\u306A\u3044\u5834\u5408\u306F\u81EA\u52D5\u7684\u306B\u4F5C\u6210\u3055\u308C\u307E\u3059\u3002\u5143\u306E\u30D5\u30A9\u30EB\u30C0\u69CB\u9020\u306F\u79FB\u884C\u5148\u3067\u3082\u7DAD\u6301\u3055\u308C\u307E\u3059\u3002"
    });
  }
};
